// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/base-form/index.vue')['default']
    HtmlToCanvasWrap: typeof import('./src/components/html-to-canvas-wrap/index.vue')['default']
    LeftCircleOutlined: typeof import('@ant-design/icons-vue')['LeftCircleOutlined']
    PageContainer: typeof import('./src/components/page-container/index.vue')['default']
    PageHeader: typeof import('./src/components/page-header/index.vue')['default']
    RightCircleOutlined: typeof import('@ant-design/icons-vue')['RightCircleOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanList: typeof import('vant/es')['List']
    WidgetFullscreen: typeof import('./src/components/page-header/widget-fullscreen.vue')['default']
    WidgetUser: typeof import('./src/components/page-header/widget-user.vue')['default']
  }
}
